# Project 2, Part 5, Cleansing customer data

University of California, Berkeley

Master of Information and Data Science (MIDS) program

w205 - Fundamentals of Data Engineering

Student: Landon Morin

Year: 2022

Semester: Spring

Section: 9

# Included Modules and Packages

Code cell containing your includes for modules and packages

In [1]:
import math
import numpy as np
import pandas as pd
import time

import psycopg2

import json

import csv

from datetime import datetime as dt

from IPython.display import display, HTML

from jellyfish import soundex, levenshtein_distance

from fuzzywuzzy import fuzz

from fuzzywuzzy import process as fuzz_process

# Supporting code

Code cells containing any supporting code, such as connecting to the database, any functions, etc.  

Remember you can freely use any code from the labs. You do not need to cite code from the labs.

In [2]:
connection = psycopg2.connect(
    user = "postgres",
    password = "ucb",
    host = "postgres",
    port = "5432",
    database = "postgres"
)

In [3]:
cursor = connection.cursor()

In [4]:
#
# function to run a select query and return rows in a pandas dataframe
# pandas puts all numeric values from postgres to float
# if it will fit in an integer, change it to integer
#

def my_select_query_pandas(query, rollback_before_flag, rollback_after_flag):
    "function to run a select query and return rows in a pandas dataframe"
    
    if rollback_before_flag:
        connection.rollback()
    
    df = pd.read_sql_query(query, connection)
    
    if rollback_after_flag:
        connection.rollback()
    
    # fix the float columns that really should be integers
    
    for column in df:
    
        if df[column].dtype == "float64":

            fraction_flag = False

            for value in df[column].values:
                
                if not np.isnan(value):
                    if value - math.floor(value) != 0:
                        fraction_flag = True

            if not fraction_flag:
                df[column] = df[column].astype('Int64')
    
    return(df)

# 2.5.1 Validate the city, state, and zip for stage_1_peak_customers against the zip_codes table

AGM does not want to give its customer list to 3rd party sales channels, including Peak Delivery.  For that reason, we can expect some variation in customer first and last names, and in the street.  However, the city, state, and zip should be validated by Peak's system, so we do not anticipate any issues.

Write a query that demonstrates that the city, state, and zip are valid for all records.  Like we did in 2.4, it's usually best to write a query that return errors.  In our case the query should not return anything.

Sort by stage_id

Pattern your code after the examples in the labs.  You may use as many code cells as you need.

In [5]:
rollback_before_flag = True
rollback_after_flag = True

query  = """

select *
from stage_1_peak_customers
where (city, state, zip) not in (select city, state, zip from zip_codes)
order by stage_id


"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

Empty DataFrame
Columns: [stage_id, sale_id, customer_id, first_name, last_name, street, city, state, zip]
Index: []

# 2.5.2 Find all customer records in stage_1_peak_customers where any of first_name, last_name, and/or street do not match a customer in the customers table

AGM does not want to give its customer list to 3rd party sales channels, including Peak Delivery.  For that reason, we can expect some variation in customer first and last names, and in the street.  

Write a query that returns all customer records in state_1_peak_customers where any of the first_name, last_name, and/or street do not match a customer in the customers table

Sort by stage_id

Pattern your code after the examples in the labs.  You may use as many code cells as you need.

In [6]:
rollback_before_flag = True
rollback_after_flag = True

query  = """

select *
from stage_1_peak_customers
where (first_name, last_name, street) not in (select first_name, last_name, street from customers)
order by stage_id


"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

,stage_id,sale_id,customer_id,first_name,last_name,street,city,state,zip
0,10,5763728768,3729016,Hyrum,Knuckles,86668 Spenser Terrace,Oakland,CA,94618
1,20,5763728877,3728936,Roseann,Coyish,11707 American Ash Ter,Orinda,CA,94563
2,24,5763728428,3729287,Hali,Ducker,8 Orion Pass,El Cerrito,CA,94530
3,26,5763728393,3728674,Melantha,Golborn,6140 North Field Alley,Orinda,CA,94563
4,36,5763729212,3729191,Eleni,Jansen,66 Bartelt Hill,Oakland,CA,94607
5,40,5763729129,3728856,Clyve,Humonds,22 Brent Wood Hill,Berkeley,CA,94709
6,51,5763728864,3729178,Rutledge,Hellwing,606 Gulf Plz,El Cerrito,CA,94530
7,60,5763729313,3728402,Kalli,Kemel,18373 Golf View Pass,Berkeley,CA,94702
8,72,5763728980,3729213,Honina,Philson,28 Clarendon Plaza,Berkeley,CA,94702
9,73,5763728921,3729194,Nicky,Haley,88424 Warrior Lane,Oakland,CA,94602
10,75,5763729280,3729104,I,Odunniom,4243 Sugar Park,Berkeley,CA,94702
11,78,5763728905,3729208,Clemens,McAloren,12532 Faragut Lane,Berkeley,CA,94704
12,97,5763728673,3728691,Eula,Dewair,3 Crownhardt Road,Albany,CA,94706

# 2.5.3 Find the percentage of Peak's customer records that do not match to AGM's customers table

Write a query to find the percentage of Peak's customer records that do not match AGM's.  The percentage can be found by taking the number of customer records in stage_1_peak_customers that do not match and dividing by the number of customers records in stage_1_peak_customers and multiplying by 100.

Show the total number of Peak customer records in stage_1_peak_customers, the number that match to customers, the number that do not match to customers, and the percentage that do not match.

Show the percentage rounded to the nearest tenth.  It is not necessary to include a percent sign.

Pattern your code after the examples in the labs.  You may use as many code cells as you need.

In [7]:
rollback_before_flag = True
rollback_after_flag = True

query  = """

with a as (select count(customer_id) as non_matching_customers_total
           from stage_1_peak_customers
           where (first_name, last_name, street) not in (select first_name, last_name, street from customers)), 
           
b as (select count(customer_id) as total_customers
      from stage_1_peak_customers)
           
select total_customers, non_matching_customers_total, 
       b.total_customers - a.non_matching_customers_total as total_matching_customers,
       round(a.non_matching_customers_total::numeric/b.total_customers::numeric*100,1) as peak_unmatched_customer_percentage
from a, b



"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

,total_customers,non_matching_customers_total,total_matching_customers,peak_unmatched_customer_percentage
0,97,13,84,13.4

# 2.5.4 Executive summary on customer data

Write an executive summary on the customer data.  

The summary should be the equivalent to 3/4 to 1 page using standard fonts, spacing, and margins. 

As stated in the scenario, like most companies, AGM does not want to give out its customer list to 3rd party sales channels.  The downside is, as we have seen, that customer first names, last names, and street addresses will have some variations and not be exact matches.

The executives would like your recommendation of one of the following:
* Continue to withhold the customer data from 3rd party sales channels
* Give customer data to 3rd party sales channels

Recommend exactly one of these.

Support you recommendation with an explanation based on what you have seen from this preliminary data load.

You are not required to write any queries nor create any data visualizations.  However, you may want to include some to enhance and add quality to your submission.  Submissions with these tend to be higher quality, although, not always.

You may use any number of code cells and/or markdown cells. 

You may alternate between code cells and markdown cells.  That is perfectly fine.  It is understood that before we present it, an editor would pull out the text, results of queries, and data visualizations.

In [8]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select c.customer_id,
       pc.first_name as peak_first,
       pc.last_name as peak_last,
       c.first_name as agm_first, 
       c.last_name as agm_last,
       pc.street as peak_street, 
       c.street as agm_street
from stage_1_peak_customers as pc
    join customers as c
         on pc.zip = c.zip
where (pc.first_name, pc.last_name, pc.street) not in (select c.first_name, c.last_name, c.street from customers)
order by stage_id



"""
cursor.execute(query)

connection.rollback()
    
rows = cursor.fetchall()

In [9]:

start = time.time()

for row in rows:
    if (levenshtein_distance(row[1], row[3]) < 4 and 
    levenshtein_distance(row[2], row[4]) < 4 and 
    levenshtein_distance(row[5], row[6]) < 4):
        print("---------------------------------------------------------")
        print('Possible AGM Customer id:', row[0])
        print('First Name PEAK:', row[1], '\nFirst Name AGM:', row[3])
        print('Last Name PEAK:' , row[2], '\nLast Name AGM:', row[4])
        print('Address PEAK:' , row[5], '\nAddress AGM:', row[6])
        print("Levenshtein Distance First Name:", levenshtein_distance(row[1], row[3]))
        print("Levenshtein Distance Last Name:", levenshtein_distance(row[2], row[4]))
        print("Levenshtein Distance Street:", levenshtein_distance(row[5], row[6]))


end = time.time()
print('time:', end - start)

---------------------------------------------------------
Possible AGM Customer id: 281
First Name PEAK: Hyrum
First Name AGM: Hiram
Last Name PEAK: Knuckles
Last Name AGM: Knuckles
Address PEAK: 86668 Spenser Terrace
Address AGM: 86668 Spenser Terrace
Levenshtein Distance First Name: 2
Levenshtein Distance Last Name: 0
Levenshtein Distance Street: 0
---------------------------------------------------------
Possible AGM Customer id: 3163
First Name PEAK: Hali
First Name AGM: Halli
Last Name PEAK: Ducker
Last Name AGM: Ducker
Address PEAK: 8 Orion Pass
Address AGM: 8 Orin Pass
Levenshtein Distance First Name: 1
Levenshtein Distance Last Name: 0
Levenshtein Distance Street: 1
---------------------------------------------------------
Possible AGM Customer id: 2271
First Name PEAK: Melantha
First Name AGM: Melantha
Last Name PEAK: Golborn
Last Name AGM: Golborn
Address PEAK: 6140 North Field Alley
Address AGM: 6140 Northfield Alley
Levenshtein Distance First Name: 0
Levenshtein Distance Last Name: 0
Levenshtein Distance Street: 2
---------------------------------------------------------
Possible AGM Customer id: 2565
First Name PEAK: Eleni
First Name AGM: Eleni
Last Name PEAK: Jansen
Last Name AGM: Jansen
Address PEAK: 66 Bartelt Hill
Address AGM: 6 Bartelt Hill
Levenshtein Distance First Name: 0
Levenshtein Distance Last Name: 0
Levenshtein Distance Street: 1
---------------------------------------------------------
Possible AGM Customer id: 1267
First Name PEAK: Clyve
First Name AGM: Clyve
Last Name PEAK: Humonds
Last Name AGM: Hammonds
Address PEAK: 22 Brent Wood Hill
Address AGM: 22 Brentwood Hill
Levenshtein Distance First Name: 0
Levenshtein Distance Last Name: 2
Levenshtein Distance Street: 2
---------------------------------------------------------
Possible AGM Customer id: 2938
First Name PEAK: Rutledge
First Name AGM: Rutledge
Last Name PEAK: Hellwing
Last Name AGM: Hellwing
Address PEAK: 606 Gulf Plz
Address AGM: 606 Golf Plaza
Levenshtein Distance First Name: 0
Levenshtein Distance Last Name: 0
Levenshtein Distance Street: 3
---------------------------------------------------------
Possible AGM Customer id: 1053
First Name PEAK: Kalli
First Name AGM: Kalli
Last Name PEAK: Kemel
Last Name AGM: Kemell
Address PEAK: 18373 Golf View Pass
Address AGM: 18373 Golf View Pass
Levenshtein Distance First Name: 0
Levenshtein Distance Last Name: 1
Levenshtein Distance Street: 0
---------------------------------------------------------
Possible AGM Customer id: 1136
First Name PEAK: Honina
First Name AGM: Junina
Last Name PEAK: Philson
Last Name AGM: Philson
Address PEAK: 28 Clarendon Plaza
Address AGM: 28 Clarendon Plaza
Levenshtein Distance First Name: 2
Levenshtein Distance Last Name: 0
Levenshtein Distance Street: 0
---------------------------------------------------------
Possible AGM Customer id: 3342
First Name PEAK: Nicky
First Name AGM: Nickey
Last Name PEAK: Haley
Last Name AGM: Haley
Address PEAK: 88424 Warrior Lane
Address AGM: 88424 Warrior Lane
Levenshtein Distance First Name: 1
Levenshtein Distance Last Name: 0
Levenshtein Distance Street: 0
---------------------------------------------------------
Possible AGM Customer id: 539
First Name PEAK: Clemens
First Name AGM: Klemens
Last Name PEAK: McAloren
Last Name AGM: MacAloren
Address PEAK: 12532 Faragut Lane
Address AGM: 12532 Farragut Lane
Levenshtein Distance First Name: 1
Levenshtein Distance Last Name: 1
Levenshtein Distance Street: 1
---------------------------------------------------------
Possible AGM Customer id: 1820
First Name PEAK: Eula
First Name AGM: Eula
Last Name PEAK: Dewair
Last Name AGM: Deware
Address PEAK: 3 Crownhardt Road
Address AGM: 3 Crownhardt Road
Levenshtein Distance First Name: 0
Levenshtein Distance Last Name: 2
Levenshtein Distance Street: 0
time: 0.47875404357910156

In [10]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select *
from stage_1_peak_customers
where (first_name, last_name, street) not in (select first_name, last_name, street from customers)
order by stage_id



"""

nonmatch = my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

In [11]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select *
from customers
order by customer_id



"""

agm = my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

In [12]:
dfa = pd.DataFrame({'customer':[]})
dfa['customer'] = agm['first_name']+', '+agm['last_name']+", "+agm['street']

In [13]:
dfp = pd.DataFrame({'customer':[]})
dfp['customer'] = nonmatch['first_name']+', '+nonmatch['last_name']+", "+nonmatch['street']

In [14]:
dfp

                                     customer
0      Hyrum, Knuckles, 86668 Spenser Terrace
1     Roseann, Coyish, 11707 American Ash Ter
2                  Hali, Ducker, 8 Orion Pass
3   Melantha, Golborn, 6140 North Field Alley
4              Eleni, Jansen, 66 Bartelt Hill
5          Clyve, Humonds, 22 Brent Wood Hill
6            Rutledge, Hellwing, 606 Gulf Plz
7          Kalli, Kemel, 18373 Golf View Pass
8         Honina, Philson, 28 Clarendon Plaza
9            Nicky, Haley, 88424 Warrior Lane
10               I, Odunniom, 4243 Sugar Park
11      Clemens, McAloren, 12532 Faragut Lane
12            Eula, Dewair, 3 Crownhardt Road

In [15]:
peak_unmatched_list = dfp['customer'].to_list()
peak_unmatched_list

['Hyrum, Knuckles, 86668 Spenser Terrace',
 'Roseann, Coyish, 11707 American Ash Ter',
 'Hali, Ducker, 8 Orion Pass',
 'Melantha, Golborn, 6140 North Field Alley',
 'Eleni, Jansen, 66 Bartelt Hill',
 'Clyve, Humonds, 22 Brent Wood Hill',
 'Rutledge, Hellwing, 606 Gulf Plz',
 'Kalli, Kemel, 18373 Golf View Pass',
 'Honina, Philson, 28 Clarendon Plaza',
 'Nicky, Haley, 88424 Warrior Lane',
 'I, Odunniom, 4243 Sugar Park',
 'Clemens, McAloren, 12532 Faragut Lane',
 'Eula, Dewair, 3 Crownhardt Road']

In [16]:
agm_customer_list = dfa['customer'].to_list()
agm_customer_list

['Robb, Weaving, 5 Ramsey Place',
 'Robby, Belliard, 6 Londonderry Plaza',
 'Sadella, Caudrelier, 548 Mcguire Parkway',
 'Holmes, Shimmings, 99 Kennedy Court',
 'Beverley, Gubbin, 51 Mcbride Drive',
 'Pavia, Millery, 463 Columbus Pass',
 'Engracia, Jeanon, 24 Hanover Court',
 'Melinda, Stodd, 568 Nova Way',
 'Dinnie, Leek, 38 Golf Alley',
 'Caitrin, Filipowicz, 61 Michigan Drive',
 'Sybille, Vipan, 75841 2nd Hill',
 'Genevieve, Roughey, 129 Katie Street',
 'Artie, Brandes, 3744 Troy Circle',
 'Matilda, Keynes, 73 Grayhawk Park',
 'Carmina, Wandrey, 96472 Stephen Alley',
 'Tailor, Ades, 50 Union Center',
 'Davidson, Stapleton, 5 2nd Way',
 'Julio, Vearncomb, 600 Crownhardt Drive',
 'Alysa, Laight, 8 Sunfield Hill',
 'Ragnar, Keeping, 3 Iowa Avenue',
 'Kara, Faulder, 2928 Aberg Drive',
 'Edie, Wholesworth, 9393 Crescent Oaks Parkway',
 'Laurene, Righy, 85651 Daystar Pass',
 'Elvyn, Rucklesse, 38 Becker Center',
 'Theodore, Knaggs, 25 Katie Center',
 'Putnam, Heaford, 471 Knutson Place',
 'Richart, Scimonelli, 8 Mallard Way',
 'Janith, Balbeck, 45917 Red Cloud Way',
 'Wainwright, Armatage, 4050 Mccormick Crossing',
 'Gherardo, Iacovone, 489 Continental Way',
 'Yovonnda, Orhrt, 6738 Bayside Hill',
 'Giffard, Grayne, 303 Debs Center',
 'Tiffi, Raywood, 1 Brown Point',
 'Melloney, Bernet, 1 Northfield Circle',
 'Leilah, Henner, 2 Prairie Rose Avenue',
 'La verne, Deniscke, 32 Lyons Avenue',
 'Konstance, Divina, 84 Brentwood Parkway',
 'Cassaundra, Sadat, 7301 Corscot Parkway',
 'Garnet, Pearne, 701 Tomscot Park',
 'Nadiya, Wearing, 65 Jenna Way',
 'Camile, Lorrain, 93240 Messerschmidt Road',
 'Rebekkah, Alywen, 9533 Sloan Circle',
 'Byrom, Lawlor, 6 Dixon Avenue',
 'Clemente, Burles, 4 Monument Park',
 'Arnaldo, Bampkin, 802 Stone Corner Drive',
 'Silvano, Satyford, 77 Veith Plaza',
 'Vasilis, Seilmann, 154 Vermont Plaza',
 'Carey, Betjes, 33327 Warner Alley',
 'Kassie, Scholtis, 8 Northview Point',
 'Renault, Gunstone, 7827 Northwestern Court',
 'Claybourne, de Banke, 30 Erie Parkway',
 'Dulcinea, Fernier, 92 Oneill Pass',
 'Agnella, Hattrick, 607 Old Gate Place',
 'Lilllie, Giblett, 54066 Ronald Regan Center',
 'Hermann, Teideman, 54 American Circle',
 'Elvira, Mockett, 305 Crescent Oaks Circle',
 'Gertrude, Cook, 846 Morrow Hill',
 'Brewster, Morriss, 4202 8th Crossing',
 'Emmi, Phythien, 1277 Gerald Park',
 'Ivar, Sieghart, 66 Express Plaza',
 'Hi, Bool, 177 Colorado Drive',
 'Joelynn, Brotherick, 37 Dahle Court',
 'Dougy, Ricioppo, 6145 Sage Hill',
 'Aylmer, Flew, 1 Hooker Plaza',
 'Angel, Cobbin, 37892 Springs Avenue',
 'Donaugh, Danilishin, 943 Truax Circle',
 'Lanni, Pickavant, 481 Moose Pass',
 'Torrie, Paike, 2 Jenifer Point',
 'Hyman, McCotter, 8234 Katie Pass',
 'Licha, Domerque, 7 Morrow Junction',
 'Chicky, Nazareth, 80 International Point',
 'Cazzie, Leftridge, 1 Claremont Parkway',
 'Thomasine, Antos, 882 Eagan Circle',
 'Clarence, Matthai, 69496 Derek Center',
 'Correna, Aldus, 62 Anzinger Court',
 'Anne-corinne, Crinkley, 3530 4th Crossing',
 'Ximenez, Collicott, 811 Westport Court',
 'Yulma, Wrate, 5 West Place',
 'Maible, Korf, 79892 Victoria Avenue',
 'Ephraim, Lago, 5 Pleasure Crossing',
 'Madelyn, Gossington, 699 Lake View Park',
 'Miguel, Ceaplen, 4582 Hayes Crossing',
 'Forester, Peggrem, 73969 Bobwhite Trail',
 'Jed, Britto, 8 Loeprich Park',
 'Corbett, Storah, 4477 North Park',
 'Henri, Alliott, 6515 Briar Crest Parkway',
 'Michaela, Preene, 4102 Shelley Alley',
 'Loralee, Hamil, 818 Butterfield Place',
 'Rycca, Ferrarini, 4935 Dixon Lane',
 'Bryanty, Cunradi, 331 Clove Parkway',
 'Charmion, Constantinou, 8379 Farmco Parkway',
 'Britt, Lane, 943 Sage Pass',
 'Rafa, Audry, 47547 Bashford Lane',
 'Jeno, Gorbell, 92507 Warner Place',
 'Vanda, Sheers, 886 Pearson Point',
 'Rona, Gifkins, 526 Northridge Crossing',
 'Kassi, Tavner, 27 Waywood Crossing',
 'Joanna, Coursor, 462 Welch Circle',
 'Anne, Grene, 624 Gale Drive',
 'Ronna, Amberson, 3646 Sommers Drive',
 'Mufinella, Bugbird, 2 Duke Avenue',
 'Dulcinea, Yukhin, 377 Morrow Street',
 'Kristel, Gail, 5311 Cardinal Drive',
 'Larina, Glacken, 1855 Golf Course Trail',
 'Vikki, De Domenico, 67728 Iowa Hill',
 'Chase, Follet, 108 Heffernan Terrace',
 'Hewe, Ismirnioglou, 73 Kinsman Way',
 'Ardys, Colbourn, 6 Almo Way',
 'Emmerich, Tsar, 7 Mitchell Parkway',
 'Gilly, Campbell, 6709 Paget Place',
 'Madlin, Matieu, 9829 Carioca Alley',
 'Celie, Booker, 2943 Badeau Place',
 'Wallie, Alabone, 91049 Meadow Ridge Center',
 'Sigvard, Kerner, 51 Schurz Place',
 'Sidonnie, Kurton, 8450 Vahlen Place',
 'Darrelle, Dohrmann, 46 Farwell Terrace',
 'Kikelia, Ryrie, 758 Schmedeman Avenue',
 'Prentice, Milborn, 5508 Warrior Pass',
 'Pippa, Royle, 82 Dexter Point',
 'Son, Tyler, 7 Esker Street',
 'Britt, Hanretty, 944 Elgar Drive',
 'Tanya, Brightman, 6388 Waubesa Street',
 'Greggory, Elstob, 736 Leroy Hill',
 'Catina, Filkin, 61 Lindbergh Circle',
 'Priscella, Maynard, 59218 Morning Lane',
 'Teresa, Dearden, 999 Mallory Court',
 'Hercules, Quincey, 9 Vahlen Plaza',
 'Reginauld, Adamkiewicz, 4218 Duke Plaza',
 'Rafaela, Roglieri, 38900 Tennessee Drive',
 'Laverna, Dolby, 11 Beilfuss Park',
 'Reta, Kennerley, 92 Rigney Point',
 'Margareta, Probbin, 53551 Orin Crossing',
 'Cyrill, Ezzle, 53735 Banding Avenue',
 'Merrile, Sawyers, 3370 Hayes Park',
 'Thacher, Kramer, 9448 Stuart Parkway',
 'Torrence, MacIlhagga, 36311 Butternut Place',
 'Arlana, Lemoir, 33 School Road',
 'Jeffry, Gyse, 2 Derek Way',
 'Morley, Twinberrow, 3 Dottie Plaza',
 'Nelie, Monkleigh, 12951 Homewood Junction',
 'Michelina, Jewell, 565 Farmco Alley',
 'Matti, Wellard, 8 Carberry Parkway',
 'Haslett, Maeer, 8037 Village Terrace',
 'Willie, Broadbury, 76016 Ramsey Plaza',
 'Craggy, Demangeon, 59 Waubesa Pass',
 'Stanislas, Berzen, 8928 Carioca Park',
 'Shurlocke, Newell, 9 Bay Trail',
 'Marthena, Oxberry, 9 Atwood Junction',
 'Asher, Siggery, 7 Summerview Plaza',
 'Jasmina, Shilton, 669 Everett Avenue',
 'Basilio, Syder, 579 Clarendon Crossing',
 'Barri, Rentoll, 8819 Sycamore Plaza',
 'Junie, Brislawn, 890 Arapahoe Court',
 'Natalina, Dobbins, 7 Old Shore Drive',
 'Vallie, Bagg, 11 Green Way',
 'Nehemiah, Grut, 55 Schmedeman Point',
 'Abrahan, Dytham, 78157 Pleasure Hill',
 'Crawford, Cope, 63 Petterle Park',
 'Darbee, Bielfeldt, 8 Haas Terrace',
 'Chauncey, Southerden, 8 Gulseth Lane',
 'Fran, Kleisel, 83223 Manley Terrace',
 'Tory, Mountney, 2 Basil Center',
 'Kevyn, Emmatt, 7 Norway Maple Drive',
 'Freeland, Shambrooke, 98 Valley Edge Road',
 'Lutero, Redwall, 620 Havey Parkway',
 'Giacobo, Parcells, 68 Becker Parkway',
 'Edita, Worrill, 38 Bluejay Park',
 'Mervin, Belsher, 69222 Lerdahl Pass',
 'Nolly, Smitham, 247 Everett Place',
 'Dita, Parchment, 423 Warner Way',
 'Dela, Biddell, 46384 Farwell Hill',
 'Merwin, Hanrahan, 3 Alpine Way',
 'Halley, Anneslie, 47 Gateway Point',
 'Cosimo, Leeming, 90639 Meadow Ridge Way',
 'Jordain, St. Hill, 78787 Northfield Pass',
 'Gregor, Patters, 47 Thierer Parkway',
 'Kalila, Abby, 61607 Homewood Street',
 'Fitz, Magne, 4051 Monterey Park',
 'Thea, Gritton, 97629 Golden Leaf Trail',
 'Meier, Ambroise, 1 Mifflin Crossing',
 'Eugenius, Degg, 2 Ridgeview Circle',
 'Conchita, Gerge, 953 Sutherland Crossing',
 'Lorelle, Kiledal, 3 Clove Terrace',
 'Annabelle, Rennox, 31513 Luster Place',
 'Franz, Quartly, 95896 Moose Pass',
 'Floyd, McCrossan, 99 Veith Circle',
 'Dalila, Sowray, 4860 Burning Wood Road',
 'Morna, Dainter, 6 Cardinal Road',
 'Pepito, Costello, 69 Ryan Terrace',
 'Eydie, Chawner, 35 Little Fleur Drive',
 'Ethelbert, Ainsley, 7269 Farwell Avenue',
 'Ric, Shorey, 992 Del Sol Junction',
 'Daphna, Maffione, 6547 Shopko Park',
 'Dasi, Ghelardoni, 2410 Armistice Alley',
 'Dav, Gresham, 8 Farmco Plaza',
 'Shel, Denkel, 875 Little Fleur Trail',
 'Lind, Roust, 54481 Meadow Ridge Circle',
 'Matthiew, Willshee, 48 Sommers Parkway',
 'Charlotta, Rossi, 6 Dayton Alley',
 'Gaby, Cahani, 3229 Daystar Drive',
 'Margalit, Benediktsson, 5220 Almo Circle',
 'Paola, Gherarducci, 9849 Prairieview Park',
 'Dyna, Beckford, 84 Eastwood Hill',
 'Fonzie, Cuddehy, 14 Hagan Drive',
 'Gardy, Forrestor, 1648 Bunker Hill Circle',
 'Uriah, Breache, 16452 Crowley Way',
 'Brendan, Nibloe, 34583 Main Road',
 'Abagael, Wren, 4 Green Circle',
 'Simeon, Downey, 44296 Sheridan Pass',
 'Tonie, Hamp, 7073 Huxley Terrace',
 'Hyman, Bliss, 701 Dahle Place',
 'Babara, Meake, 7 Nancy Street',
 'Sindee, Paulisch, 547 Rowland Road',
 'Dag, Symcox, 7249 Manley Crossing',
 'Fina, Blaise, 93 Northfield Park',
 'Aubrey, Gude, 62 Loeprich Avenue',
 'Lonnie, Lecointe, 9139 Northridge Circle',
 'Timoteo, Copeland, 79 Meadow Ridge Court',
 'Cesare, Cadany, 4306 Hintze Court',
 'Cletis, Banbrigge, 383 Hudson Parkway',
 'Guendolen, Bartosiak, 2705 Marquette Drive',
 'Kriste, Hebdon, 31 Di Loreto Junction',
 'Brianna, Pestridge, 664 Melby Terrace',
 'Philomena, Lghan, 996 Larry Circle',
 'Paulie, Buss, 624 Southridge Parkway',
 'Forester, De Fraine, 14052 Coleman Hill',
 'Bernette, Newens, 32 Eagan Point',
 'Aguste, Nye, 126 Crowley Terrace',
 'Norman, Lidgett, 690 Hovde Alley',
 'Carleen, Dubbin, 8325 Fallview Road',
 'Fabien, Blann, 15 Vermont Terrace',
 'Celestine, Sigge, 889 Raven Terrace',
 'Oralle, Letertre, 639 Brentwood Circle',
 'Nanete, Castagne, 84 Lakewood Gardens Drive',
 'Nonie, Jefferys, 61812 Del Sol Parkway',
 'Clyve, Greste, 3599 Thackeray Alley',
 'Loree, Lanphere, 22 Shelley Terrace',
 'Isa, Gobel, 6 Stuart Place',
 'Devon, Forcer, 1183 Sutherland Drive',
 'Penny, Boughen, 2 Lakewood Gardens Lane',
 'Anya, Hallstone, 923 Hollow Ridge Point',
 'Adah, Whal, 8851 Utah Road',
 'Wyatt, Giacovazzo, 3 Little Fleur Park',
 'Ellwood, Jeffcoate, 38275 Cherokee Lane',
 'Allyn, Grinyov, 2443 Lien Way',
 'Anders, Jurasek, 98 Texas Junction',
 'Merrick, Pringley, 684 Troy Center',
 'Annabell, Penniall, 17 Schiller Circle',
 'Kym, Girardin, 4315 Westport Junction',
 'Tomas, Tebbs, 50553 Bay Plaza',
 'Law, Abramson, 8 Onsgard Park',
 'Conny, Dosdale, 4 Melvin Pass',
 'Jaquelin, MacAne, 6 Lindbergh Pass',
 'Orton, Smedmore, 40 Westend Place',
 'Guss, Skahill, 8857 Montana Place',
 'Korry, Bento, 28367 Scott Circle',
 'Jarrad, Touhig, 1 Stoughton Junction',
 'Maribeth, Titmus, 40693 Red Cloud Center',
 'Kelsey, Ranklin, 529 Stone Corner Crossing',
 'Chrotoem, Whannel, 19199 Northport Circle',
 'Tamiko, Stearley, 54993 Loftsgordon Alley',
 'Terri, McGlynn, 82309 Sauthoff Drive',
 'Grantley, Baus, 3 Logan Circle',
 'Velvet, Stainland, 75 Myrtle Drive',
 'Rayshell, Vinas, 596 Graedel Terrace',
 'Walliw, Casley, 250 Duke Parkway',
 'Teena, Kesteven, 3964 Bay Terrace',
 'Brew, Dive, 19 Beilfuss Center',
 'Chev, Symondson, 7438 Carioca Drive',
 'Gordon, Thewlis, 6490 Kingsford Hill',
 'Darby, Fensome, 33 Talisman Place',
 'Kimberlee, Kalderon, 6 Oxford Place',
 'Gearalt, Broadley, 651 Sunbrook Circle',
 'Flora, Sunner, 2 Dottie Alley',
 'Connor, Janeway, 54 Blaine Pass',
 'Dynah, McMenemy, 2 Sunfield Hill',
 'Agnese, Boldt, 515 Truax Place',
 'Christabel, Crake, 46294 Clove Park',
 'Morgun, Featherstonehaugh, 86046 Mitchell Point',
 'Sephira, Belton, 25315 Marquette Junction',
 'Hiram, Knuckles, 86668 Spenser Terrace',
 'Kirby, Gullivent, 932 Spaight Street',
 "Launce, O'Mullaney, 99 Sachtjen Street",
 'Starlin, Ebbutt, 1646 Thackeray Park',
 'Ursula, Enric, 9587 Cascade Junction',
 'Stacy, Treverton, 8 Gateway Pass',
 'Vivie, Pullen, 1 Michigan Park',
 'Clovis, Hackworthy, 83 Alpine Street',
 'Ingram, Pavek, 54 Canary Trail',
 "Peta, O'Crowley, 8 Briar Crest Place",
 'Wenona, McDougle, 74320 Starling Terrace',
 'Rubetta, Queste, 8 Vidon Court',
 'Rutger, Seale, 423 Fair Oaks Trail',
 'Melisse, Giddons, 471 Vidon Center',
 'Lilas, Dukelow, 88790 Daystar Junction',
 'Lynn, Kubicek, 44 Shopko Terrace',
 'Matilda, Wileman, 8909 Fallview Avenue',
 'Adelice, Cosyns, 95594 Kennedy Alley',
 'Leonanie, Whitrod, 408 Hansons Crossing',
 'Angel, Hutchason, 1322 Gulseth Point',
 'Jeffy, Oty, 11 Blackbird Lane',
 'Farleigh, Pendreigh, 61 Ohio Terrace',
 'Rourke, Darville, 67851 Banding Trail',
 'Gale, Petel, 901 8th Circle',
 'Nikita, Newis, 7 Bellgrove Avenue',
 'Eddie, Odda, 38 Doe Crossing Park',
 'Whitaker, Lotte, 431 Grim Road',
 'Amandy, Dolby, 42 Express Center',
 'Brenda, Fields, 72926 Ludington Parkway',
 'Denise, Mantrip, 7641 Hermina Park',
 'Britteny, Flather, 81 Meadow Ridge Street',
 'Lavinie, Allwright, 924 Sauthoff Way',
 'Torrin, Fideler, 88 Esch Junction',
 'Bren, Collishaw, 76580 Saint Paul Way',
 'Phaedra, Pleven, 92139 Towne Park',
 'Rabi, McCawley, 5272 Bluejay Crossing',
 'Gayelord, Domenc, 677 Sutteridge Place',
 'Frankie, Barry, 16349 Reinke Circle',
 'Waiter, Tsar, 39896 Northwestern Court',
 'Garik, Cruse, 88 Mitchell Hill',
 'Retha, Howle, 48047 Straubel Circle',
 'Tally, Watling, 13 Eagle Crest Hill',
 'Krispin, Djokic, 17014 Stang Pass',
 'Haskell, Feakins, 43107 Eagle Crest Road',
 'Marya, Odam, 415 Ramsey Avenue',
 'Ryann, Kanwell, 7934 Holmberg Place',
 'Benni, Cox, 6671 Ramsey Crossing',
 'Rawley, Gynni, 6161 Center Way',
 'Hazel, Nano, 2490 Di Loreto Street',
 'Abby, Aujean, 5 Mandrake Place',
 "Jolie, O'Corrin, 1 Cody Crossing",
 'Marianne, Beckey, 17 Vahlen Parkway',
 'Carce, Inkpin, 3 Drewry Trail',
 'Gray, Brownsea, 73348 Grayhawk Hill',
 'Mariam, Liepina, 7 Melrose Street',
 'Merwin, MacVicar, 9 Atwood Alley',
 'Morly, Kimberley, 9686 Pennsylvania Drive',
 'Beverley, Etheredge, 18011 Bultman Center',
 'Angelle, Biscomb, 651 Wayridge Avenue',
 'Ephrayim, Fludder, 98 Karstens Center',
 'Teddy, Godard, 58 Mayer Pass',
 'Donica, Bowlas, 6 Bowman Alley',
 'Issie, Glazzard, 42 Dovetail Drive',
 'Frasquito, Streatley, 858 Hoepker Plaza',
 'Freida, Hannis, 4 Haas Alley',
 'Gregoire, Eckhard, 58462 Porter Road',
 'Claire, Cardow, 6196 Alpine Pass',
 'Layney, Cestard, 39 Myrtle Lane',
 'Theresina, Sebring, 6749 Jana Circle',
 'Garland, Fenemore, 118 Clarendon Drive',
 'Melosa, Foulser, 6589 Buhler Trail',
 'Thorny, Lipmann, 492 Waubesa Crossing',
 'Cacilia, Bartkiewicz, 7758 Manley Lane',
 'Essie, Moore, 8 Menomonie Circle',
 'Gabbey, Hain, 44 High Crossing Hill',
 'Sally, Gilfillan, 737 Kropf Road',
 'Sallyanne, Ruller, 43 Victoria Hill',
 'Raffaello, MacGowan, 90714 Fulton Lane',
 'Gare, Pryke, 92351 Hanson Pass',
 'Dallis, Pegg, 447 3rd Terrace',
 'Katheryn, Chagg, 66193 Carioca Alley',
 'Anett, Staniforth, 94 Jackson Terrace',
 'Cecelia, Meece, 33 Westend Point',
 'Georgianne, Preist, 800 Hallows Crossing',
 'Elmira, Spelman, 819 Dennis Terrace',
 'Robin, Presswell, 4590 Hallows Road',
 'Alyce, Barnson, 4636 Judy Road',
 'Maurits, Farbrother, 68 Harper Alley',
 'Thaine, Karp, 32169 Kropf Park',
 'Bartholemy, Marzellano, 6979 Anhalt Parkway',
 'Brear, Rembrandt, 1 Schurz Hill',
 'Francesca, Rosenqvist, 65 Darwin Center',
 'Prentiss, Dumberrill, 6885 Sutteridge Circle',
 'Daisey, Ridgeway, 28721 Sunnyside Pass',
 'Tania, Marishenko, 120 Victoria Way',
 'Alex, Muehler, 1 Anderson Pass',
 'Nikki, Galbraeth, 6 Elka Lane',
 'Onofredo, Hutchinges, 6561 Main Court',
 'Ivett, Flarity, 23 Lighthouse Bay Court',
 'Mariele, Noads, 5 Mifflin Pass',
 'Vivia, Darthe, 55595 Namekagon Road',
 'Ravi, Cargill, 5 Spohn Plaza',
 'Sabine, Scotts, 73663 Swallow Circle',
 'Haleigh, Beenham, 680 Mendota Crossing',
 'Gayle, MacGarrity, 286 Onsgard Center',
 'Rodrique, Pride, 2 Donald Court',
 'Robers, Capstack, 87 Rutledge Point',
 'Montague, Jochanany, 9 Menomonie Junction',
 'Charley, Torr, 883 Cambridge Court',
 'Lita, Darnborough, 63 Fallview Alley',
 'Garwin, Smullen, 6768 Dwight Road',
 "Marchall, O'Neal, 6049 8th Pass",
 'Ansley, Hucks, 1 Eagan Parkway',
 'Glenda, Bonnavant, 864 Golf View Trail',
 'Clem, Ledgley, 5 Merchant Junction',
 'Reed, Birks, 2959 Bartelt Way',
 'Borg, Dainter, 4983 Towne Place',
 'Sallyann, Lawie, 43 Brentwood Parkway',
 'Teena, Rodrigo, 62694 Old Gate Plaza',
 'Constance, Le Batteur, 8813 Burrows Parkway',
 'Jodee, Halsted, 2 Vidon Lane',
 'Bertrando, Logan, 81847 Bluejay Alley',
 'Clary, Craiker, 12 Milwaukee Avenue',
 'Allen, Linnane, 4 Northwestern Place',
 'Olly, Wevell, 5767 Anhalt Point',
 'Ceciley, Kingwell, 4165 Dahle Alley',
 'Caril, Jendrassik, 4 Mayfield Junction',
 'Yevette, Dundin, 6 Bluejay Park',
 'Louie, Huddleston, 9289 Loftsgordon Court',
 'Harmony, Chaffer, 7 Duke Road',
 'Olly, Larkby, 333 Merrick Avenue',
 'Filbert, Jeens, 65 Emmet Avenue',
 'Doug, Dore, 74771 Heffernan Circle',
 'Codi, Dericut, 74 Hudson Court',
 "Gena, O'Fergus, 82 Lukken Way",
 'Lianna, Fuidge, 22707 Stang Center',
 'Gavra, Shillom, 40868 Montana Point',
 'Robyn, Gosnold, 2 Leroy Street',
 'Cassius, Brougham, 8 Sage Street',
 'Dulcie, Lachaize, 58 Lakewood Pass',
 'Denis, Spadollini, 31 Hooker Avenue',
 'Melinda, Iannello, 2 Eliot Terrace',
 'Joli, Sans, 96807 Chive Alley',
 'Celine, Colliver, 68 Mockingbird Circle',
 'Liuka, Tancock, 68308 Mcbride Road',
 'Ralph, Spinola, 483 Tomscot Crossing',
 'Stafford, Edwick, 6819 Dennis Place',
 'Curtis, Helis, 98 Browning Crossing',
 'Nelle, Quarton, 1 Eliot Park',
 'Donna, Truluck, 41901 Eliot Plaza',
 'Deeann, Allaker, 8 Starling Center',
 'Gertrudis, Sergant, 8 Arrowood Plaza',
 'Oralie, Sach, 5390 Scoville Terrace',
 'Simonne, Choules, 8 Logan Junction',
 'Roth, Macauley, 24461 Eastwood Alley',
 'Francois, Van den Velden, 4362 Columbus Alley',
 'Noland, Argo, 59966 Old Shore Place',
 'Homer, Robuchon, 8109 Surrey Hill',
 'Babara, Franklyn, 151 Steensland Drive',
 'Catherina, Alejandri, 79140 Morrow Crossing',
 'Idell, Merrison, 6 Hollow Ridge Center',
 'Helsa, Holdin, 9145 Bartelt Street',
 'Engelbert, Dufour, 114 Eagle Crest Crossing',
 'Quintilla, Kassel, 885 Welch Lane',
 'Isaiah, Cicconettii, 9915 Sullivan Circle',
 'Hoyt, Peattie, 4 Scott Terrace',
 'Riki, Vernall, 40 Cherokee Place',
 'Carly, Rubens, 5 Havey Park',
 'Eleen, Slopier, 539 Grover Alley',
 'Shannen, Fenton, 191 Sachs Crossing',
 'Jess, Godar, 95152 Forster Trail',
 'Jed, Manuele, 132 Mosinee Junction',
 'Aurelie, Lehrian, 544 Londonderry Park',
 'Dorena, Titcom, 420 Charing Cross Place',
 'Scott, Saggs, 78 Hoffman Street',
 'Kipp, Thirlaway, 2793 Arrowood Lane',
 'Cathlene, Andreotti, 91 Fremont Parkway',
 'Ham, Bigrigg, 95989 Evergreen Road',
 'Terri, Litster, 70 Oakridge Street',
 'Shaun, Cleaver, 1 Dennis Drive',
 'Tarah, Matura, 4 Gina Park',
 'Adella, Ramsell, 40 Wayridge Crossing',
 'Slade, Cope, 52 Sugar Court',
 'Claretta, McGeoch, 79753 Crest Line Circle',
 'Avis, Pond, 402 Porter Drive',
 'Theresina, Fear, 44436 Prairieview Pass',
 'Lee, Tenman, 85 Warrior Road',
 'Barbaraanne, Toping, 78 Red Cloud Road',
 'Bard, Martelet, 94480 Blackbird Avenue',
 'Norine, Enright, 1621 Calypso Plaza',
 'Carlyn, Dooney, 179 Pond Lane',
 'Krystalle, Irlam, 90663 Bartillon Center',
 'Jody, Lye, 373 Forest Dale Parkway',
 'Glenn, Chawkley, 8 Monterey Alley',
 'Madelene, Firbank, 4346 Gina Crossing',
 'Pippa, Linley, 526 Pond Pass',
 'Collie, Flye, 956 Sunnyside Center',
 'Nell, Slany, 2 Porter Court',
 'Leif, Abel, 66649 Kedzie Trail',
 'Daile, Howgego, 544 Crescent Oaks Circle',
 'Arne, Oliphand, 25 Mayer Parkway',
 'Giff, Everett, 6818 Toban Circle',
 'Marc, Congram, 2191 Waywood Circle',
 'Elwin, Featherstone, 2187 Melody Junction',
 'Caressa, Giacobilio, 802 Hagan Street',
 'Flossy, Vain, 4 Browning Trail',
 'Matty, Yellowlees, 5695 Scott Drive',
 'Bryon, Dorking, 269 Cambridge Crossing',
 'Hasheem, Maryska, 16 Portage Circle',
 'Viviana, Terrans, 9 Warbler Avenue',
 'Colan, Bunclark, 1474 Fairfield Plaza',
 'Hamid, Coronado, 54 Algoma Trail',
 'Saundra, Emma, 23974 Northport Alley',
 'Lanni, Garrad, 3 Rusk Avenue',
 'Dorolisa, Harvey, 89488 Hauk Road',
 'Susie, Neicho, 4 Browning Way',
 'Leroy, Clericoates, 69978 Kensington Plaza',
 'Booth, Poile, 74607 Westridge Way',
 'Rania, Kuhnt, 46747 Pepper Wood Road',
 'Morley, Larkcum, 4 Claremont Alley',
 'Randolph, MacDearmaid, 97015 Hoepker Crossing',
 'Mariya, Bare, 39044 Anzinger Road',
 'Kathryn, Samarth, 58638 Center Terrace',
 'Boyd, Brownbill, 4850 Paget Parkway',
 'Stefan, Elphinstone, 6 Sullivan Junction',

In [17]:
start = time.time()
match_list = []
for cust in peak_unmatched_list:
    match_list.append(fuzz_process.extract(cust, agm_customer_list, limit = 1))
end = time.time()
print('time:', end - start)

time: 16.840769052505493

In [18]:
match_list

[[('Hiram, Knuckles, 86668 Spenser Terrace', 95)],
 [('Roseann, Coyish, 11707 American Ash Terrace', 95)],
 [('Halli, Ducker, 8 Orin Pass', 96)],
 [('Melantha, Golborn, 6140 Northfield Alley', 99)],
 [('Eleni, Jansen, 6 Bartelt Hill', 98)],
 [('Clyve, Hammonds, 22 Brentwood Hill', 94)],
 [('Rutledge, Hellwing, 606 Golf Plaza', 94)],
 [('Kalli, Kemell, 18373 Golf View Pass', 99)],
 [('Junina, Philson, 28 Clarendon Plaza', 94)],
 [('Nickey, Haley, 88424 Warrior Lane', 98)],
 [("Israel, O'Dunniom, 4243 Sugar Park", 90)],
 [('Klemens, MacAloren, 12532 Farragut Lane', 95)],
 [('Eula, Deware, 3 Crownhardt Road', 97)]]

# Executive Summary

As our ELT and preliminary analytics have demonstrated, there can be data validation issues when using third party data. Specifically, in one day of trial-deliveries, we have found 13 customer entries in Peak's system that have not matched our customer database. This means that 13% of our customer data is inaccurate useless unless corrected. However, in our first day our analytics team have found multiple avenues for cleansing and validating Peak's customer data. Preliminary analytics for our first day of the delivery trial support our team's recommendation that we do not share our customer data with Peak or any other third party vendor. 

By employing Extract, Load, Transform (ELT) and Continually Integrating/Continually Developing (CI/CD) techniques, our analytics team is able to work with Peak's POS data quickly to resolve inaccuracies in the customer database and perform meaningful analytics. We can guarantee more accurate customer data even with streaming POS data. 

Peak's first day dataset contained 13 entries that did not match with AGM's customer database. However, by creating a script to iterate through AGM's customer entries and Peak's customer entries and to search for minimized Levenshtein Distances, we were able to shrink the error rate from 13.4\% to 2\%. Furthermore, by searching for AGM-Peak customer pairs with the highest Fuzzy Logic scores, we can reduce this error rate to 0. However, there is a time-cost associated with this method. While Fuzzy Logic will guarantee to show us the closest match, filtering by Levenshtein Distances less than 4 gives us satisfactory accuracy and is roughly 41x less time-intensive with this amount of data. At higher data levels, finding matches using Fuzzy Logic will likely become unacceptably time-intensive. Nontheless, we have two methods that will allow us to clean and use inaccurate or unclean data from Peak's database. 


Therefore, we do not recommend sharing our customer data with Peak, since there is no reward for doing so. The risks are many. Firstly, Peak may merge with a larger competitor such as Amazon. If Amazon acquires our customer data, they may be able to outcompete us in our region. Secondly, we lose control of our data, which poses great risks. We cannot guarantee that Peak will treat our customer data with the same care and respect that we do. Finally, Peak may suffer a data breach. This exposes our customers and AGM to unnecessary risks for minimal reward.